# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerOne', models.CharField(max_length=100)),
                ('PlayerTwo', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la partie')),
            ],
        ),
    ]
