# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_auto_20170306_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerID', models.IntegerField(primary_key=True, serialize=False)),
                ('PlayerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='GameID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='game',
            name='PlayerOneHand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='PlayerTwoHand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='PlayerOne',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='playerOne', to='accueil.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='PlayerTwo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='playerTwo', to='accueil.Player'),
        ),
    ]
