# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='Date',
        ),
    ]
