# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0003_auto_20170306_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='PlayerOne',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='PlayerOne', to='accueil.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='PlayerTwo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='PlayerTwo', to='accueil.Player'),
        ),
    ]
